### ISSUE TITLE
Investigate EditorJS tools

### ISSUE THREAD

**Issue by aubeOSG** [scrowl-io/web-authoring#115]
Take a look at the list of [tools](https://github.com/editor-js/awesome-editorjs#tools) that EditorJS has/promotes.

Identify the most useful content tools by comparing what the app currently has against the feature set in Notion and Sana.

Make a separate list for inline/tune tools as well as plugins.

Additionally, check out the documentation on creating a custom inline/tune tool.

Write up your findings in a Notion doc; provide the link via a comment.

**Comment by clarkeOSG** [comment]
https://www.notion.so/EditorJS-Notes-on-content-tools-cbc408b4992b471b8dfcd2ce7df1549f
